name: API Tests

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  ALLURE_ENDPOINT: ${{ vars.ALLURE_ENDPOINT }}
  ALLURE_PROJECT_ID: ${{ vars.ALLURE_PROJECT_ID }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Check Gradle
        run: |
          pwd
          ls -la gradlew
          ./gradlew --version

      - name: Setup allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}

      - name: Run tests
        run: |
          allurectl watch -- ./gradlew clean test

      - name: Check Allure results
        if: always()
        run: |
          echo "=== Allure directories ==="
          find . -type d -name "*allure*" -print

          echo "=== Allure result files ==="
          find . -type f \( \
            -name "*-result.json" -o \
            -name "*-container.json" \
          \) -print

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results
          if-no-files-found: warn