name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  ALLURE_ENDPOINT: ${{ vars.ALLURE_ENDPOINT }}
  ALLURE_PROJECT_ID: ${{ vars.ALLURE_PROJECT_ID }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Debug workspace
        run: |
          echo "Current directory:"
          pwd

          echo "Root:"
          ls -la

          echo "Gradle wrapper:"
          find . -name "gradlew" -type f -print

          echo "Build files:"
          find . -maxdepth 4 \
            \( -name "build.gradle" -o -name "build.gradle.kts" -o -name "settings.gradle" -o -name "settings.gradle.kts" \) \
            -print